steps:
  - label: "Display Dynamic Commit Link"
    command: |
      echo "Commit Hash: $BUILDKITE_COMMIT"
      echo "You can view the commit here: https://github.com/myorg/myrepo/commit/$BUILDKITE_COMMIT"

