steps:
  - label: "Display Dynamic Commit Link"
    command: |
      echo "Commit Hash: $BUILDKITE_COMMIT"
      echo "You can view the commit here: https://github.com/Damilola-obasa/Clocktime/commit//commit/$BUILDKITE_COMMIT"

